//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ColorValley.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ColorValley.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datenschutzerklärung.
        /// </summary>
        internal static string ButtonTextDataPrivacyDeclaration {
            get {
                return ResourceManager.GetString("ButtonTextDataPrivacyDeclaration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hilfe.
        /// </summary>
        internal static string ButtonTextHelp {
            get {
                return ResourceManager.GetString("ButtonTextHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🏆.
        /// </summary>
        internal static string ButtonTextHighScore {
            get {
                return ResourceManager.GetString("ButtonTextHighScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impressum.
        /// </summary>
        internal static string ButtonTextImpressum {
            get {
                return ResourceManager.GetString("ButtonTextImpressum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datenschutzerklärung der Red Valley Software GmbH für Color Valley
        ///
        ///Der Schutz Ihrer persönlichen Daten ist uns ein wichtiges Anliegen. Diese Datenschutzerklärung
        ///informiert Sie darüber, welche Daten im Rahmen der Nutzung von Color Valley erhoben und
        ///verarbeitet werden.
        ///
        ///1. Verantwortlicher
        ///Verantwortlich für die Datenverarbeitung im Zusammenhang mit der Nutzung dieser App ist:
        ///Red Valley Software GmbH
        ///Am Pumperhölzl 12, 84323 Massing
        ///E-Mail: rupert.eder@redvalley-software.com
        ///Webseite: www.redvalley-soft [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DataPrivacyMainText {
            get {
                return ResourceManager.GetString("DataPrivacyMainText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datenschutzerklärung.
        /// </summary>
        internal static string DataPrivacyPageTitle {
            get {
                return ResourceManager.GetString("DataPrivacyPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hilfe.
        /// </summary>
        internal static string HelpPageTitle {
            get {
                return ResourceManager.GetString("HelpPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In diesem Beispiel können sogar mehrere Kästchen ausgewählt werden (alle markierten Gelben Kästchen): .
        /// </summary>
        internal static string HelpTextExampleMultiMatch {
            get {
                return ResourceManager.GetString("HelpTextExampleMultiMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Im nächsten Beispiel gibt es kein passendes Kästchen. Wird dennoch ein falsches Kästchen ausgewählt, so werden Punkte abgezogen:.
        /// </summary>
        internal static string HelpTextExampleNoMatch {
            get {
                return ResourceManager.GetString("HelpTextExampleNoMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Im folgenden Beispiel kann nur ein Kästchen ausgewählt werden (das gelb markierte Blaue). Dieses hat die selbe Farbe wie das zentrale innere Kästchen:.
        /// </summary>
        internal static string HelpTextExampleSingleMatch {
            get {
                return ResourceManager.GetString("HelpTextExampleSingleMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ziel des Spiels ist es immer so schnell wie möglich die richtigen äußeren Kästchen durch Berühren mit dem Finger auszuwählen..
        /// </summary>
        internal static string HelpTextGameGoal {
            get {
                return ResourceManager.GetString("HelpTextGameGoal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das zentrale innere Kästchen gibt hierbei immer die Zielfarbe vor. Diese Farbe muss bei den äußeren Kästchen gesucht und so schnell wie möglich ausgewählt werden um Pukte zu erhalten..
        /// </summary>
        internal static string HelpTextInitial {
            get {
                return ResourceManager.GetString("HelpTextInitial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highscore Liste.
        /// </summary>
        internal static string HighScorePageTitle {
            get {
                return ResourceManager.GetString("HighScorePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impressum:
        ///Angaben nach § 5 TMG:
        ///Verantwortliche Firma:
        ///Red Valley Software GmbH
        ///Geschäftssitz: Am Pumperhölzl 12, 84323 Massing
        ///Das Unternehmen ist im Handelsregister eingetragen und gehört der Industrie- und Handelskammer
        ///(IHK) Niederbayern an (ihk@passau.ihk.de).
        ///Telefon: 08724/2071850
        ///E-Mail: 
        ///Webseite: www.redvalley-software.com
        ///Geschäftsführung: Rupert Eder
        ///Registernummer: HRB 11508
        ///Umsatzsteuer-Identifikationsnummer gem. § 27a UStG: DE322142672
        ///Programmierung: rupert.eder@redvalley-software.com
        ///
        ///Dat [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ImpressumMainText {
            get {
                return ResourceManager.GetString("ImpressumMainText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impressum.
        /// </summary>
        internal static string ImpressumPageTitle {
            get {
                return ResourceManager.GetString("ImpressumPageTitle", resourceCulture);
            }
        }
    }
}
