//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ColorValley.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ColorValley.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data privacy.
        /// </summary>
        internal static string ButtonTextDataPrivacyDeclaration {
            get {
                return ResourceManager.GetString("ButtonTextDataPrivacyDeclaration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string ButtonTextHelp {
            get {
                return ResourceManager.GetString("ButtonTextHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🏆.
        /// </summary>
        internal static string ButtonTextHighScore {
            get {
                return ResourceManager.GetString("ButtonTextHighScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imprint.
        /// </summary>
        internal static string ButtonTextImpressum {
            get {
                return ResourceManager.GetString("ButtonTextImpressum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🏃‍♂️‍➡️ Next Level.
        /// </summary>
        internal static string ButtonTextNextLevel {
            get {
                return ResourceManager.GetString("ButtonTextNextLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red Valley Software GmbH Privacy Policy for Color Valley
        ///
        ///The protection of your personal data is important to us. This privacy policy
        ///informs you about which data is collected and processed when you use Color Valley.
        ///
        ///1. Controller
        ///The controller responsible for data processing in connection with the use of this app is:
        ///Red Valley Software GmbH
        ///Am Pumperhölzl 12, 84323 Massing
        ///Email: rupert.eder@redvalley-software.com
        ///Website: www.redvalley-software.com
        ///
        ///2. Collection and Processing of Personal [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DataPrivacyMainText {
            get {
                return ResourceManager.GetString("DataPrivacyMainText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data privacy.
        /// </summary>
        internal static string DataPrivacyPageTitle {
            get {
                return ResourceManager.GetString("DataPrivacyPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string HeaderHighscoreName {
            get {
                return ResourceManager.GetString("HeaderHighscoreName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score.
        /// </summary>
        internal static string HeaderHighscoreScore {
            get {
                return ResourceManager.GetString("HeaderHighscoreScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string HelpPageTitle {
            get {
                return ResourceManager.GetString("HelpPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In this example, even multiple boxes can be selected (all marked yellow boxes):.
        /// </summary>
        internal static string HelpTextExampleMultiMatch {
            get {
                return ResourceManager.GetString("HelpTextExampleMultiMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In the next example, there is no matching box. If an incorrect box is selected, points are deducted:.
        /// </summary>
        internal static string HelpTextExampleNoMatch {
            get {
                return ResourceManager.GetString("HelpTextExampleNoMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In the following example, only one box can be selected (the blue one marked in yellow). This has the same color as the central inner box:.
        /// </summary>
        internal static string HelpTextExampleSingleMatch {
            get {
                return ResourceManager.GetString("HelpTextExampleSingleMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The aim of the game is to select the correct outer boxes as quickly as possible by touching them with your finger..
        /// </summary>
        internal static string HelpTextGameGoal {
            get {
                return ResourceManager.GetString("HelpTextGameGoal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The central inner box always indicates the target color. This color must be searched for in the outer boxes and selected as quickly as possible to score points..
        /// </summary>
        internal static string HelpTextInitial {
            get {
                return ResourceManager.GetString("HelpTextInitial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highscore List.
        /// </summary>
        internal static string HighScorePageTitle {
            get {
                return ResourceManager.GetString("HighScorePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legal Notice:
        ///Information according to Section 5 of the German Telemedia Act (TMG):
        ///Responsible company:
        ///Red Valley Software GmbH
        ///Headquarters: Am Pumperhölzl 12, 84323 Massing
        ///The company is registered in the commercial register and is a member of the Lower Bavaria Chamber of Industry and Commerce (IHK) (ihk@passau.ihk.de).
        ///Telephone: +49 8724 2071850
        ///Email:
        ///Website: www.redvalley-software.com
        ///Management: Rupert Eder
        ///Registration number: HRB 11508
        ///VAT identification number according to Section 2 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ImpressumMainText {
            get {
                return ResourceManager.GetString("ImpressumMainText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impressum.
        /// </summary>
        internal static string ImpressumPageTitle {
            get {
                return ResourceManager.GetString("ImpressumPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ... or change your player name 
        ///(for the highscore list):.
        /// </summary>
        internal static string LabelLaunchChangePlayerName {
            get {
                return ResourceManager.GetString("LabelLaunchChangePlayerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello 🙂.
        /// </summary>
        internal static string LabelLaunchFirstTime {
            get {
                return ResourceManager.GetString("LabelLaunchFirstTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or look at the instructions first:.
        /// </summary>
        internal static string LabelLaunchFirstTimeHelp {
            get {
                return ResourceManager.GetString("LabelLaunchFirstTimeHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello {0} 🙂.
        /// </summary>
        internal static string LabelLaunchNotFirstTime {
            get {
                return ResourceManager.GetString("LabelLaunchNotFirstTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🏆 Super {0} - New high score!!!
        ///You have {1} points!.
        /// </summary>
        internal static string LabelLaunchNotFirstTimeNewHighScore {
            get {
                return ResourceManager.GetString("LabelLaunchNotFirstTimeNewHighScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🎖 Great {0}
        ///You have {1} points!.
        /// </summary>
        internal static string LabelLaunchNotFirstTimeNewScore {
            get {
                return ResourceManager.GetString("LabelLaunchNotFirstTimeNewScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🙁 Too bad {0}, unfortunately you have zero points!.
        /// </summary>
        internal static string LabelLaunchNotFirstTimeNoScore {
            get {
                return ResourceManager.GetString("LabelLaunchNotFirstTimeNoScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your player name here for the highscore list:.
        /// </summary>
        internal static string LabelLaunchPlayerName {
            get {
                return ResourceManager.GetString("LabelLaunchPlayerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to start right away?.
        /// </summary>
        internal static string LabelLaunchStart {
            get {
                return ResourceManager.GetString("LabelLaunchStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🏆 Top Score: {0} ⭐️ {1}.
        /// </summary>
        internal static string LabelLaunchTopScore {
            get {
                return ResourceManager.GetString("LabelLaunchTopScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level:.
        /// </summary>
        internal static string LabelLevelText {
            get {
                return ResourceManager.GetString("LabelLevelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🍋 Easy peasy lemon squeezy.
        /// </summary>
        internal static string Level1Name {
            get {
                return ResourceManager.GetString("Level1Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🤸‍♂️ Quick slick turbo trick.
        /// </summary>
        internal static string Level2Name {
            get {
                return ResourceManager.GetString("Level2Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🕹 Much too much mega clutch.
        /// </summary>
        internal static string Level3Name {
            get {
                return ResourceManager.GetString("Level3Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🎨 Bright light color delight.
        /// </summary>
        internal static string Level4Name {
            get {
                return ResourceManager.GetString("Level4Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🌈 Flash dash color splash.
        /// </summary>
        internal static string Level5Name {
            get {
                return ResourceManager.GetString("Level5Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Valley.
        /// </summary>
        internal static string MainPageTitle {
            get {
                return ResourceManager.GetString("MainPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This app is ad-supported 😉, the game starts immediately after the following advertisement....
        /// </summary>
        internal static string SplashWelcomeAddExplaination {
            get {
                return ResourceManager.GetString("SplashWelcomeAddExplaination", resourceCulture);
            }
        }
    }
}
